security:
    enable_authenticator_manager: true
    # Configuration pour le hachage des mots de passe
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto  # Vous pouvez utiliser 'auto', 'bcrypt', 'argon2id', etc.
        # Configuration pour PasswordAuthenticatedUserInterface
        Symfony\Component.Security.Core.User.PasswordAuthenticatedUserInterface:
            algorithm: auto
    # Configuration des fournisseurs d'utilisateurs
    providers:
        # Utilisateur provider
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email
    # Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

            # Activer différents moyens d'authentification
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Contrôles d'accès
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/user/\d+/ban, roles: [ADMIN] }
        - { path: ^/admin/user/\d+/unban, roles: [ADMIN] }

when@test:
    security:
        password_hashers:
            # Configuration des hashers de mots de passe pour les tests
            Symfony\Component.Security.Core.User.PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur la plus basse pour bcrypt
                time_cost: 3 # Valeur la plus basse pour argon
                memory_cost: 10 # Valeur la plus basse pour argon
