<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Categorie extends \App\Entity\Categorie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'idCategorie', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'espacecouvert', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'espaceenfants', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'espacefumeur', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'servicerestauration', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'espacepartenaire'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'idCategorie', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'espacecouvert', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'espaceenfants', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'espacefumeur', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'servicerestauration', '' . "\0" . 'App\\Entity\\Categorie' . "\0" . 'espacepartenaire'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Categorie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCategorie(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCategorie();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCategorie', []);

        return parent::getIdCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function isEspacecouvert(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEspacecouvert', []);

        return parent::isEspacecouvert();
    }

    /**
     * {@inheritDoc}
     */
    public function setEspacecouvert(bool $espacecouvert): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspacecouvert', [$espacecouvert]);

        return parent::setEspacecouvert($espacecouvert);
    }

    /**
     * {@inheritDoc}
     */
    public function isEspaceenfants(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEspaceenfants', []);

        return parent::isEspaceenfants();
    }

    /**
     * {@inheritDoc}
     */
    public function setEspaceenfants(bool $espaceenfants): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspaceenfants', [$espaceenfants]);

        return parent::setEspaceenfants($espaceenfants);
    }

    /**
     * {@inheritDoc}
     */
    public function isEspacefumeur(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEspacefumeur', []);

        return parent::isEspacefumeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setEspacefumeur(bool $espacefumeur): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspacefumeur', [$espacefumeur]);

        return parent::setEspacefumeur($espacefumeur);
    }

    /**
     * {@inheritDoc}
     */
    public function isServicerestauration(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isServicerestauration', []);

        return parent::isServicerestauration();
    }

    /**
     * {@inheritDoc}
     */
    public function setServicerestauration(bool $servicerestauration): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServicerestauration', [$servicerestauration]);

        return parent::setServicerestauration($servicerestauration);
    }

    /**
     * {@inheritDoc}
     */
    public function getEspacepartenaire(): ?\App\Entity\Espacepartenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEspacepartenaire', []);

        return parent::getEspacepartenaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setEspacepartenaire(?\App\Entity\Espacepartenaire $espacepartenaire): \App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspacepartenaire', [$espacepartenaire]);

        return parent::setEspacepartenaire($espacepartenaire);
    }

}
