<?php

namespace ContainerRFiqPxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZBMh2aEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZBMh2aE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZBMh2aE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'type' => ['privates', '.errored..service_locator.ZBMh2aE.App\\Entity\\Type', NULL, 'Cannot autowire service ".service_locator.ZBMh2aE": it references class "App\\Entity\\Type" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'type' => 'App\\Entity\\Type',
        ]);
    }
}
