<?php

namespace ContainerRFiqPxi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEspacepartenaire2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Vsqvb_X.App\Entity\Espacepartenaire' shared service.
     *
     * @return \App\Entity\Espacepartenaire
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Vsqvb_X": it references class "App\\Entity\\Espacepartenaire" but no such service exists.');
    }
}
