index:
  path: /
  controller: App\Controller\HelloController::index
# config/routes.yaml
app_rendez_vous_stats:
    path: /rendez/vous/stats
    controller: App\Controller\RendezVousController::stats
    methods: ['GET']
analyse_pdf:
    path: /pdf
    controller: App\Controller\AnalyseController::pdf
# config/routes.yaml
analyse_detail:
    path: '/analyse/{id}'
    controller: 'App\Controller\AnalyseController::show'
app_espacepartenaire_accept:
    path: '/backoffice/espacepartenaire/{idEspace}/accept'
    controller: 'App\Controller\AdminUserController::acceptEspacepartenaire'
    methods: ['POST']

app_espacepartenaire_remove:
    path: '/backoffice/espacepartenaire/{idEspace}/delete'
    controller: 'App\Controller\AdminUserController::deleteEspacepartenaire1'
    methods: ['POST']
