<?php

namespace ContainerHmFxNNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ia5HldZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ia5HldZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ia5HldZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'espacepartenaire' => ['privates', '.errored..service_locator.Ia5HldZ.App\\Entity\\Espacepartenaire', NULL, 'Cannot autowire service ".service_locator.Ia5HldZ": it references class "App\\Entity\\Espacepartenaire" but no such service exists.'],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'espacepartenaire' => 'App\\Entity\\Espacepartenaire',
        ]);
    }
}
