<?php

namespace ContainerHmFxNNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getType2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZBMh2aE.App\Entity\Type' shared service.
     *
     * @return \App\Entity\Type
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ZBMh2aE": it references class "App\\Entity\\Type" but no such service exists.');
    }
}
