<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRFiqPxi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRFiqPxi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRFiqPxi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRFiqPxi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRFiqPxi\App_KernelDevDebugContainer([
    'container.build_hash' => 'RFiqPxi',
    'container.build_id' => '2d03dd1a',
    'container.build_time' => 1714316996,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRFiqPxi');
